export enum Type {
    FORMATION_HUMAINE_SOCIALE = 'FORMATION_HUMAINE_SOCIALE',
    IMMERSION_ENTREPRISE = 'IMMERSION_ENTREPRISE',
    INGÉNIEUR = 'INGÉNIEUR',
    NON_OBLIGATOIRE = 'NON_OBLIGATOIRE',
    EMPLOI = 'EMPLOI'
  }
  